name: Release from fork

on:
  pull_request:
    types: [closed]

jobs:
  release_fork:
    if: ${{ github.repository_owner != 'bedita' }}
    uses: bedita/github-workflows/.github/workflows/release.yml@feat/token
    with:
      main_branch: 'master'
      dist_branches: '["master"]'
      token: ${{ secrets.GH_RELEASE_TOKEN }}
