name: Release

on:
  pull_request:
    types: [closed]

jobs:
  release:
    uses: bedita/github-workflows/.github/workflows/release.yml@feat/token
    with:
      main_branch: 'master'
      dist_branches: '["master"]'
