name: Release

on:
  pull_request:
    types: [closed]

jobs:
  release-wf:
    uses: bedita/github-workflows/.github/workflows/release.yml@feat/token
    with:
      main_branch: 'master'
      dist_branches: '["master"]'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
